# _config.yml

# Site settings
title: APEX - Advanced Physique Enhancement Program
email: contact@example.com
description: >- 
  APEX is a science-based hypertrophy-optimized 6-day Push/Pull/Legs program 
  designed to maximize muscle growth through advanced techniques.
baseurl: "/apex" # the subpath of your site, e.g. /blog
url: "https://xdth.github.io" # the base hostname & protocol for your site
github_username: xdth
repository: xdth/apex

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Styling
sass:
  sass_dir: _sass
  style: compressed

# Collections
collections:
  workouts:
    output: true
    permalink: /:collection/:path/
  nutrition:
    output: true
    permalink: /:collection/:path/
  recovery:
    output: true
    permalink: /:collection/:path/
  techniques:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: "docs"
    values:
      layout: "default"
  - scope:
      path: "docs/workouts"
    values:
      layout: "default"
      category: "Workouts"
  - scope:
      path: "docs/nutrition"
    values:
      layout: "default"
      category: "Nutrition"
  - scope:
      path: "docs/recovery"
    values:
      layout: "default"
      category: "Recovery"
  - scope:
      path: "docs/logs"
    values:
      layout: "default"
      category: "Tracking"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .git
  - .github
  - README.md
  - LICENSE
  - CHANGELOG.md