title: APEX Training Program
description: Advanced Physique Enhancement Program - A scientifically-designed hypertrophy training system
baseurl: "/apex"
url: "https://xdth.github.io"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - CONTRIBUTING.md
  - DIRECTORY-STRUCTURE.md
  - .github/
  - LICENSE

# Footer content
footer_content: "Copyright &copy; 2025. APEX was created by dth with Claude 3.7."

# Build settings
markdown: kramdown