# Default settings for all pages
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      has_toc: true
      nav_order: 999
  -
    scope:
      path: "docs"
    values:
      layout: "page"
      parent: "Documentation"
  -
    scope:
      path: "docs/workouts"
    values:
      parent: "Workouts"
      grand_parent: "Documentation"
  -
    scope:
      path: "index.md"
    values:
      nav_order: 1